import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Automatically generated by FlutterFire

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyRekodApp());
}

class MyRekodApp extends StatelessWidget {
  const MyRekodApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'MyRekod',
      theme: ThemeData.dark(), // We will update this with DESIGN.md later
      home: const Scaffold(body: Center(child: Text("Firebase Initialized!"))),
    );
  }
}
